data:
  name: 'kawahara'
  dataset_dir: "data/dataset.h5"
  total_num: 148944
  n_train: 104261
  n_valid: 22341
  n_test: 22341
  train_size: 80
  num_workers: 4
  nt: 100
  sub: 1
  sub_t: 1
  # c: 1.0
  nu: 0.01

model:
  checkpoint_dir: '../new_code_successful/saved_models/Kawahara_model.ckpt'
  in_channel: 2
  out_channel: 1
  num_layers: 64
  in_dim: 2
  out_dim: 1
  activation: 'nn.Tanh' # PINNs with ReLU, ELU and SELU do not converge

train:
  device: [0]
  accelerator: 'gpu'
  rank: 'cuda'
  batchsize: 64   # previous was 128, 128 is best if we want to have less time
  num_workers: 2
  precision: "32-true"
  True_False: True
  max_epochs: 2
  milestones: [25, 50, 75, 100, 125, 150] # mile stones are the epochs at which the model is saved 
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss_weight: 0.9
  f_loss_weight: 0.8
  xy_loss_weight: 0.8
  data_loss_weight: 0.89
  profiler: 'advanced'  # "advanced", 'simple'
  save_dir: 'logs/checkpoints/saved_models/train/'
  save_name: 'kawahara_dl_model.pt'
  ckpt: 'logs/checkpoints/kawahara.pt'
  ckpt_freq: 25

log:
  project: 'kawahara'
  group: 'kawaharaGroup'

test:
  batchsize: 1
  ckpt: 'logs/checkpoints/saved_models/test/kawahara_dl_model.pt'

